org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# An idle build daemon gives its memory back after 15 minutes (the default is 3 hours).
org.gradle.daemon.idletimeout=900000
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.configuration-cache=true
